name: STFC Server 133 Monitor

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Python
        run: python --version

      - name: Run STFC monitor
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python monitor.py
